name: adity-Terraform-CI-CD
run-name: Terraform CI-CD Pipeline

on:
  # CI: PR created or updated against main
  pull_request:
    branches:
      - main

  # CD: PR merged and main gets updated
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  # ==========================================================
  # CI
  # ==========================================================
  terraform-ci:
    name: Terraform CI
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./environment/dev

    steps:

      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Secret scanning
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Azure authentication
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Terraform init
      - name: Terraform Init
        run: terraform init

      # 6. Terraform validation
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform linting
      - name: TFLint
        run: tflint

      # 8. IaC security scan
      - name: Checkov
        run: checkov -d . --framework terraform

      # 9. Terraform plan
      - name: Terraform Plan
        run: terraform plan


  # ==========================================================
  # CD
  # ==========================================================
  terraform-cd:
    name: Terraform Apply
    runs-on: self-hosted

    # CI must pass first
    needs: terraform-ci

    # Run only after main is updated
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Protected GitHub Environment
    environment:
      name: dev

    defaults:
      run:
        working-directory: ./environment/dev

    steps:

      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Azure authentication using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Terraform initialization
      - name: Terraform Init
        run: terraform init

      # 4. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
